universe = docker
docker_image = xinranmiao/tf_sensitivity:20221015
log = /home/xmiao27/logs/chtc_example$(job_id).log
error = /home/xmiao27/logs/chtc_example$(job_id).err
output = /home/xmiao27/logs/chtc_example$(job_id).err



executable = chtc_example.sh
arguments = $(job_id) $(n) $(d)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = args.txt, run.R

request_cpus = 1
request_memory = 1GB
request_disk = 2GB


requirements =(has_avx == true)

queue job_id, d, n from args.txt
