name: example
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.8
  - cudatoolkit=10.2
  - ipykernel
  - numpy
  - pandas
  - scipy
  - scikit-image
  - pip
  - pip:
    - torch
    - torchvision
